// Generated by CIRCT unknown git version
module IfNested(	// /home/kerry/repos/Python2Verilog/modulee.py:7
  input  [31:0] a,
                b,
  input         cond,
  output [31:0] out0
);

  assign out0 = cond ? {29'h0, $signed(a) < 32'sh4, 2'h2} : a;	// /home/kerry/repos/Python2Verilog/modulee.py:15, :19, :21, :22
endmodule
