name: pytest setup
description: "sets up pytest dependencies, iverilog and yosys"
runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
      python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r tests/requirements.txt
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Download Icarus Verilog and Utilities
      run: |
        sudo apt-get install iverilog expect

    - name: Download OSS CAD Suite for yosys
      run: |
        wget -nv https://github.com/YosysHQ/oss-cad-suite-build/releases/download/2023-08-02/oss-cad-suite-linux-x64-20230802.tgz
        tar -xzf oss-cad-suite-linux-x64-20230802.tgz
        echo "$GITHUB_WORKSPACE/oss-cad-suite/bin" >> $GITHUB_PATH
