# Mimics readthedocs Sphinx commands
# Locally run command at bottom of this file

name: sphinx docs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 sphinx
    - name: Build Sphinx
      working-directory: docs
      run: |
        sphinx-apidoc -o apidoc/ ../python2verilog
        make html
