name: Sphinx build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build HTML
        run: |
          python3 -m pip install -r tests/requirements.txt
          python3 -m pip install sphinx
          sphinx-apidoc -o docs/ python2verilog/ -F -H "Python2Verilog" -A "Kerry Wang"
          printf "import os\nimport sys\nsys.path.insert(0, os.path.abspath(\"..\"))\nadd_module_names = False\n" | cat - docs/conf.py > temp && mv temp docs/conf.py
          make -C docs/ html
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: html-docs
          path: docs/_build/html/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{github.ref == 'refs/heads/main' || github.ref == 'refs/heads/sphinx'}}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
