# Mimics readthedocs Sphinx commands
# Locally run command at bottom of this file

name: yosys synthesis

on:
  workflow_run:
    workflows: ["pytest testing"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Install oss with yosys
        run: |
          wget https://github.com/YosysHQ/oss-cad-suite-build/releases/download/2023-08-02/oss-cad-suite-linux-x64-20230802.tgz
          tar -xvzf oss-cad-suite-linux-x64-20230802.tgz
          echo "${pwd}/oss-cad-suite/bin/yosys" >> $GITHUB_PATH
          echo $GITHUB_PATH
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Run
        run: |
          ./yosys -o synth.v -p hierarchy -p proc -p opt -p memory -p opt -p fsm -p opt -f verilog tests/integration/data/integration/testing/module.sv -p stat
